version: '3.8'
services:
  app:
    build: ./backend
    ports:
      - "5500:5500"
    volumes:
      - ./backend/db.json:/app/db.json
    environment:
      - PORT=5500
      - JWT_SECRET=cambia_esto_en_produccion
    restart: unless-stopped